### ISSUE TITLE
Mouse Wheel Scrolling by Item does not always work

### ISSUE THREAD

**Issue by MikeWilliams-UK** [sbaeumlisberger/VirtualizingWrapPanel#12]
**Describe your issue**
I have set VirtualizingStackPanel.ScrollUnit="Item"

However scrolling with mouse wheel does not scroll by Item when ItemSize is set.
Scrolling by clicking on the arrows of the scroll bar works as expected.
It's reproducable in Tab2 of your examples.

![image](https://user-images.githubusercontent.com/13162784/99386511-7ff1f400-28ca-11eb-8efd-8c299def6920.png)

**Version Info**
Package Version 1.5.3
.NET Version: 4.8
OS Version: Windows 10 1903 build 18362.1139

**Comment by sbaeumlisberger** [comment]
Hi, 

that's the expected behaviour. When using the mouse wheel the VirtualizingWrapPanel scrolls 3 items by default. But it never scrolls more than the viewport, therefore it may looks like it does not scroll itemwise.

You can change the number of items scrolled by mouse wheel by setting the the property [`MouseWheelDeltaItem`](https://sbaeumlisberger.github.io/VirtualizingWrapPanel/api/WpfToolkit.Controls.VirtualizingPanelBase.html#WpfToolkit_Controls_VirtualizingPanelBase_MouseWheelDeltaItem) to an integer value.

**Comment by MikeWilliams-UK** [comment]
If that's so why does it scroll by a whole item when you click on the arrows.

**Comment by sbaeumlisberger** [comment]
That's because the implementation handling the scrollbar arrows does not use the property and scrolls fixed one item.

**Comment by sbaeumlisberger** [comment]
This difference also exists when scrolling by pixel. The mouse whell scrolls 48 pixels and arrows 16 pixels. This are the default values also used by other WPF controls.

**Comment by MikeWilliams-UK** [comment]
I shall try setting MouseWheelDeltaItem to 1 to see if it fixes our issue

**Comment by sbaeumlisberger** [comment]
Right, let me know if that solves your issue.

**Comment by MikeWilliams-UK** [comment]
Thanks, setting MouseWheelDeltaItem to 1 did the trick.
