### ISSUE TITLE
Question\Feature - ExpandItem Padding\Margin

### ISSUE THREAD

**Issue by devriesb13** [sbaeumlisberger/VirtualizingWrapPanel#18]
Hi There,

Is there a way i can add some padding\margin to the expanditem. Something like eg Padding="16,0" ? I've between applying a margin to the expanditemtemplate but it is being clipped when resizing horizontally.

This clipping only really happens when there is 1 column of data present.

Thanks

![image](https://user-images.githubusercontent.com/10214916/120744406-3f905580-c53e-11eb-9a97-802283824773.png)

**Comment by sbaeumlisberger** [comment]
Hi,

applying a margin seems to me to be the right way. The problem is that the ExpandItem inclusive margin is to wide to fit into the constraints of the panel. The expand item is not allowed to be wider as the row of the items.

It may help if you enable the StretchItems property. Then the full available width is used for the items.

**Comment by devriesb13** [comment]
Thanks, i have enabled the StretchItems property and it seems to have resoved the issue.
