### ISSUE TITLE
GridView ItemContainerStyle not applied

### ISSUE THREAD

**Issue by codedevote** [sbaeumlisberger/VirtualizingWrapPanel#3]
First of all, thanks for providing ths library : -)
I recently stumbled across your package and replaced some "not-so-good-working" virtualizing panel with this package and things now are going much smoother. 

I nevertheless stumbled across one problem. If I use the GridView - let's say in a simple WPF window - and set its ItemContainerStyle property (either by referencing a StaticResource or by defining it inline), everything works as expected. The ItemContainerStyle is applied.
If I define a style for the GridView and provide a Setter in this style that sets the ItemContainerStyle to the same StaticResource that I used before, the ItemContainerStyle is not applied. I actually don't have any clue why that fails. Can you sehd some light on this?

**Comment by sbaeumlisberger** [comment]
Hi, thanksfor using this project.

The problem is that the grid view applies a default style to the ItemContainerStyle property. This assignment has a higher priority than the item container style applied by your style.

I have fixed that by not setting the ItemContainerStyle directly. Instead, the default value of the dependency property is now overwritten.

**Comment by codedevote** [comment]
Oh wow, cool. Thanks for your quick reply and the fix. Do you have any plans on when you are going to release an updated nuget package?

**Comment by sbaeumlisberger** [comment]
The nuget package has just been released: https://www.nuget.org/packages/VirtualizingWrapPanel/1.5.1

**Comment by codedevote** [comment]
Thank you very much for taking care of this so fast. This is really awesome.
