### ISSUE TITLE
v2 orientation definition change?

### ISSUE THREAD

**Issue by mitchcapper** [sbaeumlisberger/VirtualizingWrapPanel#42]
**Describe your issue**
I am not sure if this is a bug or an actual intentional change.  Before setting Orientation=Vertical on a VirtualizingWrapPanel  meant it scrolled vertically.  Now that means horizontally.  Switching to horizontal seems to generate the previous behavior.   This line seems backwards:
https://github.com/sbaeumlisberger/VirtualizingWrapPanel/blob/de865450007d7ba09d048aa93df28a5414062891/src/VirtualizingWrapPanel/VirtualizingWrapPanel.cs#L83

Given the definition for LogicalOrientation seeming to match Orientation for most controls.  Granted it  doesn't look actually used so if a bug likely not the source of it.  However 
https://github.com/sbaeumlisberger/VirtualizingWrapPanel/blob/de865450007d7ba09d048aa93df28a5414062891/src/VirtualizingWrapPanel/VirtualizingWrapPanel.cs#L135-L137

could be it.
**Version Info**

**Comment by sbaeumlisberger** [comment]
Yes this is a intentional change as mentioned in the nuget [release notes](https://www.nuget.org/packages/VirtualizingWrapPanel/2.0.0-preview3#release-body-tab). The goal of this change is to align the behavior of the property with the standard WPF [WrapPanel ](https://learn.microsoft.com/de-de/dotnet/api/system.windows.controls.wrappanel.orientation).

**Comment by mitchcapper** [comment]
Thanks, I checked the main .md files and commit notes and didn't see anything but didn't think to check that.
