### ISSUE TITLE
If ItemSize not set, ItemSize should be max size of displayed items

### ISSUE THREAD

**Issue by DrkWzrd** [sbaeumlisberger/VirtualizingWrapPanel#7]
In `VirtualizingWrapPanel,UpdateChildSize` this fragment of code

`childSize = InternalChildren[0].DesiredSize;`  (line 114)

makes fixed bigger size children not showing entirely.

It should be

`var castChildren= InternalChildren.Cast<UIElement>();`
`var maxWidth = castChildren.Max(uielement=> uielement.DesiredSize.Width);`
`var maxHeight = castChildren.Max(uielement=> uielement.DesiredSize.Height);`
`childSize = new Size(maxWidth, maxHeight);`

**Comment by sbaeumlisberger** [comment]
Hi,

as described in the [API documentation](https://sbaeumlisberger.github.io/VirtualizingWrapPanel/api/WpfToolkit.Controls.VirtualizingWrapPanel.html#WpfToolkit_Controls_VirtualizingWrapPanel) all items (childs) must have the same size. If this can not be guaranteed by the items itself, you can set the ItemSize property.

The case that the items have different sizes is unfortunately not supported. The problem is that only the desired size of the realized items is known. Therefore, it is not possible to reliably calculate the maximum items size.
